### ISSUE TITLE
Uniform flow/dipole error

### ISSUE THREAD

**Issue by rhodrin** [ACCA-Imperial/PoTk#24]
Trying to create a uniform flow or dipole appears to return an error.

``` matlab

dv = [
      5./12
     -5./12
     ];
qv = [
      1./6
      1./6
     ];
beta = 0.0;  

D = unitDomain(dv, qv, beta);

uf = uniformFlow(1, 0.0);
W = potential(D, uf);

```

returns:

``` matlab

Undefined function or variable 'greensC0Dpxy'.

Error in dipole/setupPotential (line 147)
        d.greensXderivative = greensC0Dpxy(beta, 'x', D);

Error in uniformFlow/setupPotential (line 71)
        uf = setupPotential@dipole(uf, W);

Error in potential (line 63)
                pk = pk.setupPotential(W);

```

**Comment by ehkropf** [comment]
That will be an error from SKPrime. Are you using the release version of both branches? I'll be home later tonight to take a closer look.

**Comment by ehkropf** [comment]
Sorry, that should have said "release branches of both SKPrime and PoTk?"

**Comment by ehkropf** [comment]
It works for me if SKPrime is on the "release" branch and PoTk is on the "master" branch.

Sorry, thought I had the release made for PoTk. When that is true you should be on the "release" branch for both. (`git checkout release`).

**Comment by rhodrin** [comment]
Ah ok, the error goes away. But the results being given are incorrect.

**Comment by rhodrin** [comment]
Can probably ignore the above comment. Will do more testing tomorrow.

**Comment by ehkropf** [comment]
I too at one point thought I was having problems getting proper results from the the dipole and uniform flow. I never did set a good test for the values. Probably need to do something like compare with the product formula or the P function in a doubly connected domain.

**Comment by ehkropf** [comment]
Marked this as bug, since the uniform flow kind is clearly missing the argument to give the "scaling factor" on construction. And the task is to get it added.

Do we need such a factor for the dipole?

**Comment by ehkropf** [comment]
I just realised this might be tricky: is this factor ever a function of the location of the evaluation points in the physical domain? If not, it might just be simpler to explain that the strength parameter should have this factor included.

**Comment by rhodrin** [comment]
The scaling factor can be approximated by evaluating abs(dw/dzeta*dzeta/dz) at a point close to beta and comparing the result with the 'u' given by the user. 
My suggestion would be, work out and apply to above automatically unless an optional scaling parameter is given by the user (which they've worked out analytically or something). In general, the scaling parameter is not trivial to work out explicitly.

**Comment by ehkropf** [comment]
I added the scale parameter (follows the angle parameter). Gives warning if scale not set, but defaults to 1.
